name: elrs_backback_app
description: "ELRS Backback App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_libserialport: ^0.5.0
  geolocator: ^14.0.0
  get: ^4.6.5
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  url_launcher: ^6.1.12
  wakelock_plus: ^1.1.4
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

  elrs_telem:
    path: ../dart_elrs_telemetry
  graphx: ^1.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependency_overrides:
  # because of https://github.com/jpnurmi/flutter_libserialport/issues/128
  flutter_libserialport:
    git:
      url: https://github.com/NeariX67/flutter_libserialport
      ref: main

flutter:
  uses-material-design: true